<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-VFKJ2SC9" failures="1" tests="7" name="Test" time="68.761" errors="0" timestamp="2023-10-04T20:14:07 IST">
  <testcase classname="UberAdmin.Login_Test" name="verifyLoginWithCorrectCredentials" time="16.751"/>
  <testcase classname="UberAdmin.Login_Test" name="verifyLoginWithIncorrectCredentials" time="4.837"/>
  <testcase classname="UberAdmin.Login_Test" name="verifyLoginWithIncorrectCredentials" time="1.116"/>
  <testcase classname="UberAdmin.Login_Test" name="verifyLoginWithIncorrectCredentials" time="1.053"/>
  <testcase classname="UberAdmin.Login_Test" name="verifyLoginWithNoData" time="0.452">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at UberAdmin.Login_Test.verifyLoginWithNoData(Login_Test.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithNoData -->
  <testcase classname="UberAdmin.Create_Solo_Instructor_Test" name="CreateNewSoloInst" time="7.331"/>
  <testcase classname="UberAdmin.Forgot_Password_Test" name="ForgotPassword" time="2.369"/>
</testsuite> <!-- Test -->
